"""Add scanned_at to AuthTokens

Revision ID: 3b0deece62f7
Revises: e2412789c190
Create Date: 2024-06-23 17:25:48.793813

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b0deece62f7'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authtoken', sa.Column('scanned_in', sa.DateTime(), nullable=False))
    op.add_column('authtoken', sa.Column('scanned_out', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authtoken', 'scanned_in')
    op.drop_column('authtoken', 'scanned_out')
    # ### end Alembic commands ###
