name: Build, Test and Deploy the YATT android App

on:
  push:
    branches:
      - main
    paths:
      - 'yattt_app/**'
  pull_request:
    branches:
      - main
    #paths:
     # - 'yattt_app/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: yattt_app
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew


      - name: Run unit tests and generate Jacoco coverage report
        run: ./gradlew clean JacocoCodeCoverage

      - name: List coverage report directory
        run: ls -R yattt_app/app/build/reports/jacoco/

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: yattt_app/app/build/reports/jacoco/
          if-no-files-found: ignore
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/app/build/reports/jacoco/JacocoCodeCoverage/JacocoCodeCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    defaults:
      run:
        working-directory: yattt_app
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: yattt_android_app
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error