name: Test the YATTT Backend Service

on:
  push:
    paths:
      - 'yatt_backend/**'
  pull_request:
    paths:
      - 'yatt_backend/**'
      - 'main'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: Test backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run unit & integration tests
        run: |
          cd yatt_backend
          chmod +x test.sh
          ./test.sh

  dockerize:
    name: Create Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Compile and build the project
        run: |
          cd yatt_backend
          cargo build --release

      - name: Build & Save Docker image
        run: ./docker_action_setup.sh

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: nightly-release-${{ steps.date.outputs.date }}
          tag_name: nightly-tag-${{ steps.date.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./yatt_backend/yatt_backend_service.tar.gz
          asset_name: yatt_backend_service.tar.gz
          asset_content_type: application/gzip
