name: Build, Test and Deploy the YATT iOS App

on:
  push:
    branches: 
      - main
    paths:
      - 'yattt_ios/**'
      - 'yattt_ios_app.xcodeproj/**'
      - '.github/workflows/ios_app.yml'
  pull_request:
    branches: 
      - main
    paths:
      - 'yattt_ios/**'
      - 'yattt_ios_app.xcodeproj/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: macos-latest
        
    steps:
      - uses: actions/checkout@v4
            
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
          
      - name: List Available Simulators
        run: xcrun simctl list --json devices available

      - name: Install iOS 17.0
        run: | 
            xcodes runtimes install "iOS 17.0"
            
      - name: show sdk
        run: | 
          xcodebuild -showsdks   

      - name: show sdk
        run: | 
          xcrun simctl list runtimes

      - name: setup new test phone
        run: | 
          xcrun simctl create "iPhone 16" "com.apple.CoreSimulator.SimDeviceType.iPhone-15" "com.apple.CoreSimulator.SimRuntime.iOS-17.0"

      - name: Run Unit Tests with Coverage
        run: |
          xcodebuild test \
            -project yattt_ios_app.xcodeproj \
            -scheme yattt_ios_app \
            -sdk iphonesimulator18.2 \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.0" \
            -enableCodeCoverage YES

            
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult

  build:
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Build App
        run: |
          xcodebuild clean archive \
            -project yattt_ios_app.xcodeproj \
            -scheme yattt_ios_app \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/yattt_ios_app.xcarchive
