name: Build, Test and Deploy the YATT iOS App

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: macos-latest
        
    steps:
      - uses: actions/checkout@v4
            
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'
      - name: List Available Simulators
        run: xcrun simctl list

      - name: Check for iOS 18.2
        run: | 
          available_runtimes="$(xcrun simctl list runtimes)"

          if echo "$available_runtimes" | grep -q "^iOS 18.2"; then
            echo "iOS 18.2 runtime is already installed"
          else
            echo "iOS 18.2 runtime is not installed"
            sudo xcodes runtimes install "iOS 18.2"
          fi

      - name: Run Unit Tests with Coverage
        run: |
          xcodebuild test \
            -project yattt_ios_app.xcodeproj \
            -scheme yattt_ios_app \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=18.2" \
            -enableCodeCoverage YES
            
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult

  build:
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Build App
        run: |
          xcodebuild clean archive \
            -project yattt_ios_app.xcodeproj \
            -scheme yattt_ios_app \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $PWD/build/yattt_ios_app.xcarchive
